DirectoryListHeader: Directories
SelectAll: Select All
DirName: Name
DirOwner: Owner
FileName: File Name
UploaderName: Uploader Name
LastModificationTime: Last Modified
Back: Back
Refresh: Refresh
UploadSelected: Upload Selected File
ChooseFile: Choose File
UploadSucceeded: Upload Succeeded
UploadFailed: Upload Failed
NoDeadline: No Deadline
DeadlineIs time@Text: Deadline: #{time}
MaxFileSize size@Text: Each file not exceeding #{size}MB
FileNameFormat format@Text: File name in regex #{format}
MaxFiles n@Text: At most #{n} files
UploadRules: Upload Rules:
Settings: Settings