DirectoryListHeader: 文件夹列表
SelectAll: 全选
DirName: 名称
DirOwner: 所有者
FileName: 文件名
UploaderName: 上传者姓名
LastModificationTime: 最后修改时间
Back: 返回
Refresh: 刷新
UploadSelected: 上传选中文件
ChooseFile: 选择文件
UploadSucceeded: 上传成功
UploadFailed: 上传失败
NoDeadline: 没有DDL
DeadlineIs time@Text: DDL为#{time}
MaxFileSize size@Text: 单个文件不超过#{size}MB
FileNameFormat format@Text: 文件名格式为#{format}
MaxFiles n@Text: 最多#{n}个文件
UploadRules: 上传约束：
Settings: 设置
DownloadSelected: 下载选中
DeleteSelected: 删除选中
AddDirectory: 新建目录
Delete: 删除