name:                file-collector-frontend
version:             0.1.0.0
synopsis:            Web frontend of File Collector
# description:
# bug-reports:
license:             BSD-3-Clause
author:              Lagrand, Isumi Feng
# maintainer:
copyright:           Copyright 2019, Lagrand, Isumi Feng
category:            Web
extra-source-files:
- static/styles/**.scss
- static/*.ico

ghc-options: -Wall -Wno-simplifiable-class-constraints

default-extensions:
- OverloadedStrings
- OverloadedLists

dependencies:
- base ^>= 4.11
- file-collector-common
- aeson ^>= 1.3.1.1
- containers ^>= 0.5.11
- jsaddle ^>= 0.9.6.0
- jsaddle-dom
- reflex ^>= 0.5.0.1
- reflex-dom ^>= 0.4
- reflex-dom-core ^>= 0.4
- servant ^>= 0.14.1
- servant-reflex ^>= 0.3.4
- text ^>= 1.2
- time ^>= 1.8
- lens ^>= 4.16.1
- mtl ^>= 2.2.2
- transformers ^>= 0.5.5.0
- data-default ^>= 0.7.1.1
- shakespeare ^>= 2.0.20

custom-setup:
  dependencies:
  - base ^>= 4.11
  - Cabal ^>= 2.2
  - filepath ^>= 1.4.2
  - directory ^>= 1.3.1.5
  - mtl ^>= 2.2.2
  - transformers ^>= 0.5.5.0

library:
  source-dirs:
  - src
  c-sources:
  - csrc/**.c

executables:
  client:
    source-dirs:
    - app
    main: Main.hs
    dependencies:
    - file-collector-frontend
    when:
    - condition: impl(ghcjs)
      then:
        other-modules:
        - FileCollector.Frontend.Main.GHCJS
      else:
        other-modules:
        - FileCollector.Frontend.Main.GHCWarp
        dependencies:
        - jsaddle ^>= 0.9.6.0
        - filepath ^>= 1.4.2
        - jsaddle-warp ^>= 0.9.6.0
        - wai ^>= 3.2.1.2
        - wai-app-static ^>= 3.1.6.2
        - warp ^>= 3.2.25
        - websockets ^>= 0.12.5.2
        - optparse-applicative ^>= 0.14.3.0
