trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    sudo npm i -g sass
  displayName: Install SASS
- script: |
    sudo apt update
    sudo apt install -y libcurl4-openssl-dev libapr1-dev libaprutil1-dev libmxml-dev
    wget https://github.com/aliyun/aliyun-oss-c-sdk/archive/3.7.1.tar.gz
    mv 3.7.1.tar.gz aliyun-oss-c-sdk.tar.gz
    tar xf aliyun-oss-c-sdk.tar.gz
    cd aliyun-oss-c-sdk-3.7.1
    mkdir build && cd build
    cmake ..
    make
    sudo make install
  displayName: Install native libraries
- script: |
    git submodule init
    git submodule update --recursive
  displayName: Init Submodule
- task: DownloadSecureFile@1
  inputs:
    secureFile: int_test.json
- script: |
    mkdir -p backend/config
    cp $DOWNLOADSECUREFILE_SECUREFILEPATH backend/config/
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    export PATH=$HOME/.local/bin:$PATH
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
    cp 
    # Build the package, its tests, and its docs and run the tests
    stack test --haddock --no-haddock-deps
  displayName: Test Package
