name:                file-collector-backend
version:             0.1.0.0
synopsis:            Server for file-collector
# description:
homepage:            https://github.com/isumif/file-collector
# bug-reports:
license:             BSD-3-Clause
license-file:        LICENSE
author:              Isumi Feng
maintainer:          contact@zelinf.net
copyright:           Isumi Feng, Lagrand, Joyce Du, cwy
category:            Web

ghc-options: -Wall -fdefer-typed-holes
data-files:
- config/**.json
- devres/**.db

dependencies:
- base ^>= 4.11
- file-collector-common
- aeson ^>= 1.3.1.1
- bytestring >= 0.10.8 && < 0.11
- containers ^>= 0.5.11.0
- cryptonite >= 0.25 && < 0.26
- data-default ^>= 0.7.1
- fast-logger ^>= 2.4.11
- filepath ^>= 1.4.2
- http-date ^>= 0.0.8
- http-types ^>= 0.12.2
- lens ^>= 4.16.1
- memory ^>= 0.14.18
- monad-control ^>= 1.0.2.3
- monad-logger >= 0.3.30 && < 0.4
- mtl >= 2.2.2 && < 2.3
- optparse-applicative ^>= 0.14.3
- persistent ^>= 2.8.2
- persistent-sqlite ^>= 2.8.2
- persistent-template >= 2.5.4 && < 2.6
- resource-pool >= 0.2.3 && < 0.3
- servant >= 0.14 && < 0.16
- servant-server >= 0.14 && < 0.16
- string-interpolate ^>= 0.1.0.1
- text >= 1.2.3 && < 1.3
- time >= 1.8.0 && < 1.9
- transformers >= 0.5.5 && < 0.6
- transformers-base ^>= 0.4.5.2
- unliftio-core ^>= 0.1.2.0
- uuid ^>= 1.3.13
- wai ^>= 3.2.1.2
- warp >= 3.2.25 && < 3.3

library:
  source-dirs:
  - src
  - test/test-data
  c-sources:
  - csrc/**.c
  - csrc/**.h
  include-dirs:
  - csrc
  extra-libraries: pthread oss_c_sdk curl mxml apr-1 aprutil-1

executables:
  server:
    main: Server.hs
    source-dirs:
    - app
    dependencies:
    - file-collector-backend

tests:
  db: &dbTest
    main: Main.hs
    source-dirs:
    - test/db
    build-tools:
    - hspec-discover:hspec-discover ^>= 2.5.5
    dependencies:
    - file-collector-backend
    - hspec ^>= 2.5.5
    - QuickCheck ^>= 2.11.3
  integration:
    <<: *dbTest
    source-dirs:
    - test/integration
    dependencies:
    - file-collector-backend
    - base64-bytestring ^>= 1.0.0.2
    - directory ^>= 1.3.1.5
    - hspec ^>= 2.5.5
    - hspec-core ^>= 2.5.5
    - hspec-wai ^>= 0.9.2
    - hspec-wai-json ^>= 0.9.2
    - QuickCheck ^>= 2.11.3
    - wai-extra ^>= 3.0.24.3
