name:                file-collector-backend
version:             0.1.0.0
synopsis:            Server for file-collector
# description:
homepage:            https://github.com/isumif/file-collector
# bug-reports:
license:             BSD-3-Clause
license-file:        LICENSE
author:              Isumi Feng
maintainer:          contact@zelinf.net
copyright:           Isumi Feng, Lagrand, Joyce Du, cwy
category:            Web

ghc-options: -Wall -fdefer-typed-holes

dependencies:
- base ^>= 4.11
- file-collector-common
- servant >= 0.14 && < 0.16
- servant-server >= 0.14 && < 0.16
- warp >= 3.2.25 && < 3.3
- persistent ^>= 2.8.2
- persistent-template >= 2.5.4 && < 2.6
- persistent-sqlite ^>= 2.8.2
- resource-pool >= 0.2.3 && < 0.3
- text >= 1.2.3 && < 1.3
- bytestring >= 0.10.8 && < 0.11
- time >= 1.8.0 && < 1.9
- aeson ^>= 1.3.1.1
- monad-logger >= 0.3.30 && < 0.4
- fast-logger ^>= 2.4.11
- lens ^>= 4.16.1
- mtl >= 2.2.2 && < 2.3
- transformers >= 0.5.5 && < 0.6
- memory ^>= 0.14.18
- cryptonite >= 0.25 && < 0.26
- data-default ^>= 0.7.1
- optparse-applicative ^>= 0.14.3
- monad-control ^>= 1.0.2.3
- transformers-base ^>= 0.4.5.2
- unliftio-core ^>= 0.1.2.0
- string-interpolate ^>= 0.1.0.1
- uuid ^>= 1.3.13
- http-date ^>= 0.0.8

library:
  source-dirs:
  - src
  c-sources:
  - csrc/**.c
  - csrc/**.h
  include-dirs:
  - csrc
  extra-libraries: pthread oss_c_sdk curl mxml apr-1 aprutil-1

executables:
  server:
    main: Server.hs
    source-dirs:
    - app
    dependencies:
    - file-collector-backend

tests:
  db:
    main: Main.hs
    source-dirs:
    - test/db
    build-tools:
    - hspec-discover:hspec-discover
