name:                file-collector-common
version:             0.1.0.0
synopsis:            Common code shared by frontend and backend
# description:
# bug-reports:
license:             BSD-3-Clause
author:              Lagrand, Isumi Feng
# maintainer:
copyright:           Copyright 2019, Lagrand, Isumi Feng
category:            Web
build-type:          Simple

ghc-options: -Wall

dependencies:
- base ^>= 4.11
- aeson ^>= 1.3.1.1
- servant ^>= 0.14.1
- servant-docs ^>= 0.11.2
- text ^>= 1.2
- time ^>= 1.8
- lens ^>= 4.16.1
- bytestring ^>= 0.10.8.2
- base64-bytestring ^>= 1.0.0.2

library:
  source-dirs:
  - src

executables:
  gen-api-doc:
    main: GenApiDoc.hs
    source-dirs:
    - app
    when:
    - condition: "!impl(ghcjs)"
      dependencies:
      - file-collector-common
      - servant-docs
      - servant-pandoc
      - pandoc ^>= 2.5
      - text ^>= 1.2
